version: '3'
services:
  sockets-server:
    build:
      context: .
      dockerfile: Dockerfile-prod
    hostname: sockets-server
    networks:
      - web
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=3001
      
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - sockets-server
    networks:
      - web

networks:
  web:
    driver: bridge