version: '3'
services:
  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    hostname: rest-api
    networks:
      - web

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    hostname: mongodb
    networks:
      - web

  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - rest-api
    networks:
      - web

networks:
  web:
    driver: bridge