version: '3'
services:
  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    hostname: rest-api
    networks:
      - web
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=3000
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017

  mongodb:
    image: "mongo:latest"
    hostname: mongodb
    networks:
      - web

  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - rest-api
    networks:
      - web

networks:
  web:
    driver: bridge